// Code generated by "stringer -type=Gender"; DO NOT EDIT.

package model

//import "strconv"
//
//func _() {
//	// An "invalid array index" compiler error signifies that the constant values have changed.
//	// Re-run the stringer command to generate them again.
//	var x [1]struct{}
//	_ = x[Placebo-0]
//	_ = x[Aspirin-1]
//	_ = x[Ibuprofen-2]
//	_ = x[Paracetamol-3]
//}
//
//const _Gender_name = "PlaceboAspirinIbuprofenParacetamol"
//
//var _Gender_index = [...]uint8{0, 7, 14, 23, 34}
//
//func (i Gender) String() string {
//	if i < 0 || i >= Gender(len(_Gender_index)-1) {
//		return "Gender(" + strconv.FormatInt(int64(i), 10) + ")"
//	}
//	return _Gender_name[_Gender_index[i]:_Gender_index[i+1]]
//}
